# Generated by Django 4.1.7 on 2023-04-16 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('author_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('book_title', models.TextField()),
                ('book_desc', models.TextField()),
                ('publish_state', models.CharField(max_length=10)),
                ('last_time', models.DateField()),
                ('number_of_episode', models.CharField(max_length=10)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('episode_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('main_title', models.TextField()),
                ('sub_title', models.TextField()),
                ('refresh_time', models.DateField()),
                ('isupdated', models.CharField(default=1, max_length=10)),
                ('server_address', models.TextField(default='')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
