# Generated by Django 4.1.7 on 2023-04-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='last_time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='refresh_time',
            field=models.TextField(),
        ),
    ]
