# Generated by Django 4.1.7 on 2023-04-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_author_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='server_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
